# Generated by Django 5.2.5 on 2025-08-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterriorMaterial',
            new_name='InteriorMaterial',
        ),
    ]
