# Generated by Django 5.2.5 on 2025-08-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20250828_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interiormaterial',
            options={'ordering': ['name'], 'verbose_name': 'Interior material', 'verbose_name_plural': 'Interior materials'},
        ),
    ]
