# Generated by Django 4.2.16 on 2025-12-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['buyer', 'seller'], name='chat_chat_buyer_i_d8d297_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['seller', '-updated_at'], name='chat_chat_seller__3975fd_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['ad', 'buyer', 'seller'], name='chat_chat_ad_id_4396f9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='chat_messag_chat_id_0c7b25_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_read', 'sender'], name='chat_messag_chat_id_a8bc54_idx'),
        ),
    ]
