# Generated by Django 5.2.5 on 2025-08-28 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_interiormaterial_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('mileage', models.PositiveIntegerField(null=True)),
                ('power', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('battery_power', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('vin', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('warranty', models.BooleanField(default=False)),
                ('airbag', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('number_of_seats', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_doors', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged'), ('restored', 'Restored'), ('drowned', 'Drowned')], default='used', max_length=50)),
                ('owner_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_first_owner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
                ('drive_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.drivetype')),
                ('exterior_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exterior_color', to='catalog.color')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.fueltype')),
                ('interior_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interior_color', to='catalog.color')),
                ('interior_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.interiormaterial')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.modelcar')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.transmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/ads')),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ad')),
            ],
        ),
    ]
