# Generated by Django 4.2.16 on 2025-12-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_city_ad_country_ad_country_code_ad_full_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='air_conditioning',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='airbag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged'), ('restored', 'Restored'), ('drowned', 'Drowned')], db_index=True, default='used', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_first_owner',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='warranty',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['brand', 'model'], name='ads_ad_brand_i_341cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['brand', 'year'], name='ads_ad_brand_i_054ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['condition', 'year'], name='ads_ad_conditi_04ddfa_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['year', 'price'], name='ads_ad_year_0217bb_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['price', 'mileage'], name='ads_ad_price_45a535_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['brand', '-created_at'], name='ads_ad_brand_i_af8ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user', '-created_at'], name='ads_ad_user_id_2a5cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['condition', '-price'], name='ads_ad_conditi_c0b5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['-price'], name='ads_ad_price_1988c7_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['-created_at'], name='ads_ad_created_131ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['-mileage'], name='ads_ad_mileage_8d60eb_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user', 'created_at'], name='ads_ad_user_id_6799eb_idx'),
        ),
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['user', '-created_at'], name='ads_favouri_user_id_d3ffee_idx'),
        ),
    ]
